import React,{useEffect,useRef,useState} from 'react';import{createRoot}from'react-dom/client';import*as THREE from 'three';import{OrbitControls}from 'three/addons/controls/OrbitControls.js';import'./style.css';

const TYPES={plaine:{icon:'🌾',temp:1,humidity:5,wind:0},montagne:{icon:'⛰️',temp:-6,humidity:12,wind:18},foret:{icon:'🌲',temp:-2,humidity:18,wind:-8},desert:{icon:'🏜️',temp:9,humidity:-28,wind:12},ocean:{icon:'🌊',temp:2,humidity:32,wind:25},ville:{icon:'🏙️',temp:4,humidity:-5,wind:5}};
const SCENARIOS={canicule:{label:'Canicule',icon:'☀️',desc:'Air chaud et sec',type:'desert',temp:38,humidity:18,wind:12},tempete:{label:'Tempête',icon:'🌪️',desc:'Vent violent et forte humidité',type:'ocean',temp:18,humidity:88,wind:95},front:{label:'Front pluvieux',icon:'🌧️',desc:'Pluie soutenue et air humide',type:'plaine',temp:12,humidity:92,wind:35},montagne:{label:'Barrière montagneuse',icon:'🏔️',desc:'Ascendance, condensation et foehn',type:'montagne',temp:8,humidity:78,wind:55},secheresse:{label:'Sécheresse',icon:'🏜️',desc:'Air chaud, sec et peu de vent',type:'desert',temp:32,humidity:12,wind:8},mousson:{label:'Mousson',icon:'🌧️',desc:'Chaleur et humidité tropicales',type:'foret',temp:27,humidity:95,wind:48}};
const LOCAL_MODES={temperature:{label:'Température',unit:'°C',min:-20,max:45,icon:'🌡️'},humidity:{label:'Humidité',unit:'%',min:0,max:100,icon:'💧'},wind:{label:'Vent',unit:'km/h',min:0,max:120,icon:'💨'},rain:{label:'Pluie',unit:'%',min:0,max:100,icon:'🌧️'}};

function App(){const mount=useRef(null),sim=useRef(null);const windRef=useRef(15),humidityRef=useRef(55),typeRef=useRef('plaine'),runningRef=useRef(true);const localRef=useRef(null),localModeRef=useRef('temperature'),heatmapRef=useRef(true),brushRef=useRef(3);const[type,setType]=useState('plaine'),[temp,setTemp]=useState(20),[humidity,setHumidity]=useState(55),[wind,setWind]=useState(15),[scenario,setScenario]=useState('custom'),[brush,setBrush]=useState(3),[mode,setMode]=useState('raise'),[running,setRunning]=useState(true),[water,setWater]=useState(true),[relief,setRelief]=useState({lift:0,condensation:0,dryness:0,rain:0}),[localMode,setLocalMode]=useState('temperature'),[localValue,setLocalValue]=useState(20),[heatmap,setHeatmap]=useState(true),[localPoint,setLocalPoint]=useState(null);windRef.current=wind;humidityRef.current=humidity;typeRef.current=type;runningRef.current=running;

const applyScenario=(id)=>{const s=SCENARIOS[id];if(!s)return;setScenario(id);setType(s.type);setTemp(s.temp);setHumidity(s.humidity);setWind(s.wind);setLocalValue(s.temp);setRunning(true);if(localRef.current)localRef.current.reset(s.temp,s.humidity,s.wind,id==='front'||id==='tempete'?70:0)};
const resetLocal=()=>{if(localRef.current)localRef.current.reset(temp,humidity,wind,0);setLocalValue(localMode==='temperature'?temp:localMode==='humidity'?humidity:localMode==='wind'?wind:0)};
const terrain=TYPES[type];

useEffect(()=>{let alive=true;const root=mount.current,W=700,H=520;const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fd8f2);scene.fog=new THREE.Fog(0x9fd8f2,35,75);const camera=new THREE.PerspectiveCamera(50,W/H,.1,200);camera.position.set(28,25,32);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(W,H);renderer.shadowMap.enabled=true;root.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;scene.add(new THREE.HemisphereLight(0xcfefff,0x30452e,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.8);sun.position.set(-20,35,15);sun.castShadow=true;scene.add(sun);

const N=64,size=48,geo=new THREE.PlaneGeometry(size,size,N-1,N-1);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);const h=3*Math.exp(-(x*x+z*z)/220)+1.8*Math.sin(x*.24)*Math.cos(z*.19)+.7*Math.sin(x*.55+z*.3);pos.setY(i,h)}geo.computeVertexNormals();const colors=new Float32Array(pos.count*3);geo.setAttribute('color',new THREE.BufferAttribute(colors,3));const mat=new THREE.MeshStandardMaterial({color:0x4e8755,roughness:.95,vertexColors:true});const ground=new THREE.Mesh(geo,mat);ground.receiveShadow=true;ground.castShadow=true;scene.add(ground);

const waterGeo=new THREE.PlaneGeometry(size,size);waterGeo.rotateX(-Math.PI/2);const waterMat=new THREE.MeshPhysicalMaterial({color:0x2d9fd0,transparent:true,opacity:.62,roughness:.15,metalness:.05});const waterMesh=new THREE.Mesh(waterGeo,waterMat);waterMesh.position.y=0.25;scene.add(waterMesh);
function heightAt(x,z){const gx=Math.max(0,Math.min(N-1,Math.round((x+size/2)/size*(N-1)))),gz=Math.max(0,Math.min(N-1,Math.round((z+size/2)/size*(N-1))));return pos.getY(gz*N+gx)}function orographic(x,z){const h=heightAt(x,z),s=(heightAt(x+1.5,z)-heightAt(x-1.5,z))/3;return{h,up:Math.min(1,Math.max(0,s)*3+h*.02),dry:Math.min(1,Math.max(0,-s)*2.4+h*.015)}}

const treeGroup=new THREE.Group();scene.add(treeGroup);function tree(x,y,z){const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.1,7),new THREE.MeshStandardMaterial({color:0x68482e}));tr.position.y=.55;const le=new THREE.Mesh(new THREE.ConeGeometry(.65,1.8,8),new THREE.MeshStandardMaterial({color:0x2f6e3a}));le.position.y=1.55;g.add(tr,le);g.position.set(x,y,z);g.scale.setScalar(.7+Math.random()*.6);g.traverse(o=>o.castShadow=true);treeGroup.add(g)}for(let i=0;i<38;i++){const x=(Math.random()-.5)*42,z=(Math.random()-.5)*42;tree(x,heightAt(x,z),z)}

const cloudGroup=new THREE.Group();scene.add(cloudGroup);const clouds=[];for(let i=0;i<12;i++){const g=new THREE.Group();for(let j=0;j<4;j++){const s=new THREE.Mesh(new THREE.SphereGeometry(1.4+Math.random()*.9,12,8),new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.72}));s.position.set((j-1.5)*1.5,Math.random()*.6,Math.random()*.8);g.add(s)}g.position.set((Math.random()-.5)*45,14+Math.random()*8,(Math.random()-.5)*35);cloudGroup.add(g);clouds.push(g)}

const GRID=32,total=GRID*GRID;const field={temp:new Float32Array(total),hum:new Float32Array(total),wind:new Float32Array(total),rain:new Float32Array(total),nextHum:new Float32Array(total),nextTemp:new Float32Array(total),nextRain:new Float32Array(total)};
function idx(x,z){return z*GRID+x}function cellAt(x,z){return{gx:Math.max(0,Math.min(GRID-1,Math.floor((x+size/2)/size*GRID))),gz:Math.max(0,Math.min(GRID-1,Math.floor((z+size/2)/size*GRID)))}}function sampleField(x,z){const c=cellAt(x,z),i=idx(c.gx,c.gz);return{...c,index:i,temp:field.temp[i],hum:field.hum[i],wind:field.wind[i],rain:field.rain[i]}}
function resetField(t,h,w,r=0){for(let i=0;i<total;i++){field.temp[i]=t;field.hum[i]=h;field.wind[i]=w;field.rain[i]=r}updateColors();localRef.current?.setPoint(null)}
function updateColors(){for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),v=sampleField(x,z),m=LOCAL_MODES[localModeRef.current]||LOCAL_MODES.temperature;let n=(v[localModeRef.current==='rain'?'rain':localModeRef.current==='humidity'?'hum':localModeRef.current==='wind'?'wind':'temp']-m.min)/(m.max-m.min);n=THREE.MathUtils.clamp(n,0,1);const c=new THREE.Color();c.setHSL(.66-n*.66,.82,.5);colors[i*3]=heatmapRef.current?c.r:.31;colors[i*3+1]=heatmapRef.current?c.g:.53;colors[i*3+2]=heatmapRef.current?c.b:.33}geo.attributes.color.needsUpdate=true}
localRef.current={reset:(t,h,w,r)=>{resetField(t,h,w,r)},setPoint:(p)=>{setLocalPoint(p)},paint:(p,value,modeName)=>{const c=cellAt(p.x,p.z),radius=Math.max(1,Math.round(brushRef.current/size*GRID*1.5));for(let z=Math.max(0,c.gz-radius);z<=Math.min(GRID-1,c.gz+radius);z++)for(let x=Math.max(0,c.gx-radius);x<=Math.min(GRID-1,c.gx+radius);x++){const d=Math.hypot(x-c.gx,z-c.gz);if(d>radius)continue;const f=Math.cos(d/radius*Math.PI/2);const i=idx(x,z);if(modeName==='temperature')field.temp[i]=THREE.MathUtils.lerp(field.temp[i],value,f);if(modeName==='humidity')field.hum[i]=THREE.MathUtils.lerp(field.hum[i],value,f);if(modeName==='wind')field.wind[i]=THREE.MathUtils.lerp(field.wind[i],value,f);if(modeName==='rain')field.rain[i]=THREE.MathUtils.lerp(field.rain[i],value,f)}updateColors()}};
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let painting=false;const paint=(e)=>{if(!painting||mode!=='weather')return;const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(ground)[0];if(!hit)return;localRef.current.paint(hit.point,localValue,localModeRef.current);const s=sampleField(hit.point.x,hit.point.z);setLocalPoint(s)};const sculpt=(e)=>{if(!painting||mode==='weather')return;const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(ground)[0];if(!hit)return;for(let i=0;i<pos.count;i++){const dx=pos.getX(i)-hit.point.x,dz=pos.getZ(i)-hit.point.z,d=Math.sqrt(dx*dx+dz*dz);if(d<brushRef.current*2){const f=Math.cos(d/(brushRef.current*2)*Math.PI/2)*.13;let y=pos.getY(i);if(mode==='raise')y+=f;else if(mode==='lower')y-=f;else y=THREE.MathUtils.lerp(y,1,f*1.7);pos.setY(i,Math.max(-1.5,Math.min(10,y)))}}pos.needsUpdate=true;geo.computeVertexNormals()};const down=e=>{if(e.button===0){painting=true;controls.enabled=false;mode==='weather'?paint(e):sculpt(e)}};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',e=>{if(mode==='weather')paint(e);else sculpt(e)});window.addEventListener('pointerup',()=>{painting=false;controls.enabled=true});

let last=performance.now(),uiTimer=0,weatherTimer=0;function animate(now){if(!alive)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(runningRef.current){weatherTimer+=dt;if(weatherTimer>.18){weatherTimer=0;for(let z=0;z<GRID;z++)for(let x=0;x<GRID;x++){const i=idx(x,z),l=idx(Math.max(0,x-1),z),r=idx(Math.min(GRID-1,x+1),z),u=idx(x,Math.max(0,z-1)),d=idx(x,Math.min(GRID-1,z+1));const o=orographic((x/GRID-.5)*size,(z/GRID-.5)*size),adv=field.wind[i]*.0015;field.nextHum[i]=THREE.MathUtils.clamp(field.hum[i]+(field.hum[l]+field.hum[r]+field.hum[u]+field.hum[d]-4*field.hum[i])*.025+o.up*adv-o.dry*adv,0,100);field.nextTemp[i]=THREE.MathUtils.clamp(field.temp[i]+(field.temp[l]+field.temp[r]+field.temp[u]+field.temp[d]-4*field.temp[i])*.015-o.h*.004, -30,50);const rainTarget=Math.max(0,(field.nextHum[i]-72)*2.1+o.up*35-o.dry*20);field.nextRain[i]=THREE.MathUtils.clamp(field.rain[i]+(rainTarget-field.rain[i])*.08,0,100)}field.temp.set(field.nextTemp);field.hum.set(field.nextHum);field.rain.set(field.nextRain);if(heatmapRef.current)updateColors()}
const speed=(windRef.current+TYPES[typeRef.current].wind)*.035;let maxUp=0,maxDry=0;clouds.forEach(c=>{const o=orographic(c.position.x,c.position.z);maxUp=Math.max(maxUp,o.up);maxDry=Math.max(maxDry,o.dry);c.position.x+=speed*(1+o.dry*.35)*dt;if(c.position.x>30)c.position.x=-30;c.position.y=14+o.h*.35+o.up*4;c.scale.setScalar(.8+o.up*.65);c.children.forEach(m=>m.material.opacity=.5+o.up*.4-o.dry*.18)});uiTimer+=dt;if(uiTimer>.25){uiTimer=0;setRelief({lift:Math.round(maxUp*100),condensation:Math.round(maxUp*100),dryness:Math.round(maxDry*100),rain:Math.round(maxUp*Math.min(100,humidityRef.current)*.9)})}waterMesh.material.opacity=water ? .55+.08*Math.sin(now*.002) : 0;controls.update();renderer.render(scene,camera);sim.current={renderer,scene,ground,waterMesh,treeGroup};requestAnimationFrame(animate)}resetField(20,55,15);requestAnimationFrame(animate);return()=>{alive=false;renderer.dispose();window.removeEventListener('pointerup',()=>{});if(root)root.innerHTML=''}},[water]);

useEffect(()=>{if(localRef.current){localRef.current.reset(temp,humidity,wind,0)}},[type]);
useEffect(()=>{localModeRef.current=localMode;heatmapRef.current=heatmap;localRef.current?.setPoint(null);if(sim.current){const canvas=sim.current.ground?.geometry?.attributes?.color;if(canvas)canvas.needsUpdate=true}},[localMode,heatmap]);
useEffect(()=>{brushRef.current=brush},[brush]);

const sample=localPoint||{temp,hum:humidity,wind,rain:0};const effective={temp:sample.temp+terrain.temp-relief.lift*.035,hum:Math.max(0,Math.min(100,sample.hum+terrain.humidity+relief.condensation*.22-relief.dryness*.3)),wind:Math.max(0,sample.wind+terrain.wind+relief.lift*.12)};const weather=sample.rain>65&&effective.temp>0?'🌧️ Pluie locale':effective.temp<0?'❄️ Neige':relief.dryness>65?'☀️ Ombre pluviométrique':effective.hum>78?'🌧️ Pluie':'⛅ Nuageux';

return <div className="app"><header><div><span className="eyebrow">WEATHER LAB / 3D TERRAIN</span><h1>Weather Sandbox</h1><p>Sculptez le relief et peignez maintenant la météo directement sur le terrain.</p></div><div className="status">● {running?'SIMULATION ACTIVE':'PAUSE'}</div></header><main><section className="world"><div className="viewport" ref={mount}><div className="loading">Chargement du monde 3D…</div></div><div className="tools"><button className={mode==='raise'?'on':''} onClick={()=>setMode('raise')}>▲ Élever</button><button className={mode==='lower'?'on':''} onClick={()=>setMode('lower')}>▼ Creuser</button><button className={mode==='smooth'?'on':''} onClick={()=>setMode('smooth')}>◉ Lisser</button><button className={mode==='weather'?'on weather-tool':''} onClick={()=>setMode('weather')}>🌦️ Météo locale</button><label>Taille <input type="range" min="1" max="7" step=".5" value={brush} onChange={e=>setBrush(+e.target.value)}/></label><button onClick={()=>setRunning(!running)}>{running?'⏸ Pause':'▶ Reprendre'}</button></div>
<div className="readings"><div><b>{effective.temp.toFixed(1)}°C</b><span>Température locale</span></div><div><b>{effective.hum}%</b><span>Humidité locale</span></div><div><b>{Math.round(effective.wind)} km/h</b><span>Vent local</span></div><div><b>{weather}</b><span>Conditions</span></div></div></section>
<aside><div className="panel scenarios"><h2>Scénarios</h2><div className="scenario-grid">{Object.entries(SCENARIOS).map(([id,s])=><button className={scenario===id?'selected':''} onClick={()=>applyScenario(id)} key={id}><span>{s.icon}</span><div><b>{s.label}</b><small>{s.desc}</small></div></button>)}</div><button className="custom" onClick={()=>{setScenario('custom');resetLocal()}}>⚙️ Mode libre</button></div>
<div className="panel"><h2>Type de biome</h2><div className="terrain-grid">{Object.entries(TYPES).map(([id,x])=><button className={type===id?'selected':''} onClick={()=>setType(id)} key={id}><span>{x.icon}</span>{id}</button>)}</div></div>
<div className="panel local-panel"><h2>🌦️ Météo locale</h2><p className="hint">Active « Météo locale », puis clique/glisse sur le terrain pour peindre une zone météo.</p><div className="local-modes">{Object.entries(LOCAL_MODES).map(([id,x])=><button className={localMode===id?'selected':''} onClick={()=>{setLocalMode(id);setLocalValue(id==='temperature'?temp:id==='humidity'?humidity:id==='wind'?wind:0)}} key={id}>{x.icon} {x.label}</button>)}</div><Control label={LOCAL_MODES[localMode].label} value={localValue} min={LOCAL_MODES[localMode].min} max={LOCAL_MODES[localMode].max} unit={LOCAL_MODES[localMode].unit} set={setLocalValue}/><div className="local-actions"><button onClick={resetLocal}>↺ Réinitialiser</button><label className="check"><input type="checkbox" checked={heatmap} onChange={e=>setHeatmap(e.target.checked)}/> Carte thermique</label></div>{localPoint&&<div className="point-readout"><b>Point sélectionné</b><span>🌡️ {localPoint.temp.toFixed(1)}°C · 💧 {Math.round(localPoint.hum)}% · 💨 {Math.round(localPoint.wind)} km/h · 🌧️ {Math.round(localPoint.rain)}%</span></div>}<small>La météo est stockée sur une grille spatiale et évolue avec diffusion, vent, humidité et relief.</small></div>
<div className="panel"><h2>Atmosphère globale</h2><Control label="Température" value={temp} min={-30} max={45} unit="°C" set={setTemp}/><Control label="Humidité" value={humidity} min={0} max={100} unit="%" set={setHumidity}/><Control label="Vent" value={wind} min={0} max={120} unit=" km/h" set={setWind}/><label className="check"><input type="checkbox" checked={water} onChange={e=>setWater(e.target.checked)}/> Eau visible</label></div>
<div className="panel"><h2>Physique du relief</h2><p>Ascendance <strong>{relief.lift}%</strong></p><p>Condensation au vent <strong>{relief.condensation}%</strong></p><p>Zone sèche sous le vent <strong>{relief.dryness}%</strong></p><p>Pluie orographique <strong>{relief.rain}%</strong></p><small>Les pentes qui montent face au vent forcent l’air à s’élever et condensent l’humidité. Après la crête, l’air redescend et s’assèche.</small></div>
<div className="panel"><h2>Influence du biome</h2><p>Température <strong>{terrain.temp>=0?'+':''}{terrain.temp}°C</strong></p><p>Humidité <strong>{terrain.humidity>=0?'+':''}{terrain.humidity}%</strong></p><p>Vent <strong>{terrain.wind>=0?'+':''}{terrain.wind} km/h</strong></p><small>Les coefficients du biome modifient les conditions locales autour du relief.</small></div></aside></main></div>}
function Control({label,value,min,max,unit,set}){return <div className="control"><div><label>{label}</label><b>{Number(value).toFixed(Number.isInteger(value)?0:1)}{unit}</b></div><input type="range" min={min} max={max} step={label==='Température'?.5:1} value={value} onChange={e=>set(+e.target.value)}/></div>}createRoot(document.getElementById('root')).render(<App/>);