import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import*as THREE from'three';
import{OrbitControls}from'three/addons/controls/OrbitControls.js';
import'./style.css';

const TYPES={plaine:{icon:'🌾',temp:1,humidity:5,wind:0},montagne:{icon:'⛰️',temp:-6,humidity:12,wind:18},foret:{icon:'🌲',temp:-2,humidity:18,wind:-8},desert:{icon:'🏜️',temp:9,humidity:-28,wind:12},ocean:{icon:'🌊',temp:2,humidity:32,wind:25},ville:{icon:'🏙️',temp:4,humidity:-5,wind:5}};
const SCENARIOS={canicule:['☀️','Canicule','Air chaud et sec','desert',38,18,12],tempete:['🌪️','Tempête','Vent violent et forte humidité','ocean',18,88,95],front:['🌧️','Front pluvieux','Pluie soutenue et air humide','plaine',12,92,35],montagne:['🏔️','Barrière montagneuse','Ascendance, condensation et foehn','montagne',8,78,55],secheresse:['🏜️','Sécheresse','Air chaud, sec et peu de vent','desert',32,12,8],mousson:['🌧️','Mousson','Chaleur + humidité tropicales','foret',27,95,48]};
const PRESETS={archipelago:'Archipel',valley:'Vallée',coastal:'Côte',desert:'Désert',plains:'Plaines',custom:'Personnalisé'};
const LAYERS={composite:'🌍 Vue réaliste',radar:'🌧️ Radar pluie',elevation:'⛰️ Relief',temperature:'🌡️ Température',humidity:'💧 Humidité',wind:'💨 Vecteurs vent',pollution:'☁️ Pollution AQI'};
const TOOLS={raise:'▲ Élever',lower:'▼ Creuser',smooth:'◉ Lisser',heat:'🔥 Chauffer',cool:'❄️ Refroidir',humidify:'💧 Humidifier',dry:'🏜️ Assécher',pollute:'🏭 Polluer',clean:'🧼 Nettoyer air',wind_source:'💨 Source de vent',depression:'🌀 Dépression',anticyclone:'☀️ Anticyclone',thunderstorm:'⛈️ Orage',blizzard:'🌨️ Blizzard',station:'📍 Station',inspect:'🔎 Inspecter'};
const MODES={temperature:['Température','°C',-20,50],humidity:['Humidité','%',0,100],wind:['Vent','km/h',0,120],rain:['Pluie','%',0,100]};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;

function App(){
 const mount=useRef(null),E=useRef(null),R=useRef({});
 const[running,setRunning]=useState(true),[speed,setSpeed]=useState(1),[preset,setPreset]=useState('valley'),[layer,setLayer]=useState('composite'),[tool,setTool]=useState('inspect'),[brush,setBrush]=useState(5),[power,setPower]=useState(50);
 const[solar,setSolar]=useState(100),[tempOffset,setTempOffset]=useState(0),[windSpeed,setWindSpeed]=useState(15),[windDir,setWindDir]=useState(270),[pollution,setPollution]=useState(10),[evap,setEvap]=useState(100),[dayNight,setDayNight]=useState(true),[water,setWater]=useState(true);
 const[localMode,setLocalMode]=useState('temperature'),[localValue,setLocalValue]=useState(20),[heatmap,setHeatmap]=useState(false),[point,setPoint]=useState(null);
 const[station,setStation]=useState(0),[stations,setStations]=useState([]),[history,setHistory]=useState({temp:[],hum:[],wind:[],aqi:[]}),[stats,setStats]=useState({temp:0,cloud:0,rain:0,aqi:0});
 const[scenario,setScenario]=useState('custom'),[biome,setBiome]=useState('plaine'),[relief,setRelief]=useState({lift:0,dry:0,rain:0});
 R.current={running,speed,layer,tool,brush,power,solar,tempOffset,windSpeed,windDir,pollution,evap,dayNight,water,heatmap,localMode,localValue};

 useEffect(()=>{let alive=true;const root=mount.current,N=64,S=48,W=90,H=60,T=W*H,idx=(x,y)=>y*W+x;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fd8f2);scene.fog=new THREE.Fog(0x9fd8f2,38,90);
  const camera=new THREE.PerspectiveCamera(50,760/540,.1,220);camera.position.set(30,27,34);
  const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(760,540);renderer.shadowMap.enabled=true;root.appendChild(renderer.domElement);
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;scene.add(new THREE.HemisphereLight(0xd8f1ff,0x30452e,2.1));
  const sun=new THREE.DirectionalLight(0xffffff,2.7);sun.position.set(-25,38,18);sun.castShadow=true;scene.add(sun);
  const geo=new THREE.PlaneGeometry(S,S,N-1,N-1);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,col=new Float32Array(pos.count*3);geo.setAttribute('color',new THREE.BufferAttribute(col,3));
  const ground=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x4e8755,roughness:.95,vertexColors:true}));ground.receiveShadow=true;ground.castShadow=true;scene.add(ground);
  const wg=new THREE.PlaneGeometry(S,S);wg.rotateX(-Math.PI/2);const waterMesh=new THREE.Mesh(wg,new THREE.MeshPhysicalMaterial({color:0x2d9fd0,transparent:true,opacity:.6,roughness:.12}));waterMesh.position.y=.25;scene.add(waterMesh);
  const A={e:new Float32Array(T),t:new Float32Array(T),h:new Float32Array(T),u:new Float32Array(T),v:new Float32Array(T),p:new Float32Array(T),c:new Float32Array(T),r:new Float32Array(T),su:new Float32Array(T),sv:new Float32Array(T),nt:new Float32Array(T),nh:new Float32Array(T),nc:new Float32Array(T),np:new Float32Array(T)};
  const particles=Array.from({length:300},()=>({x:Math.random()*W,y:Math.random()*H,l:0,m:30+Math.random()*40}));
  const pg=new THREE.BufferGeometry(),pp=new Float32Array(900);pg.setAttribute('position',new THREE.BufferAttribute(pp,3));scene.add(new THREE.Points(pg,new THREE.PointsMaterial({color:0xffffff,size:.12,transparent:true,opacity:.65})));
  const clouds=[];const cg=new THREE.Group();scene.add(cg);for(let i=0;i<14;i++){const g=new THREE.Group();for(let j=0;j<4;j++){const m=new THREE.Mesh(new THREE.SphereGeometry(1.4+Math.random(),12,8),new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.7}));m.position.x=(j-1.5)*1.5;g.add(m)}g.position.set((Math.random()-.5)*45,15+Math.random()*7,(Math.random()-.5)*35);cg.add(g);clouds.push(g)}
  const sg=new THREE.Group();scene.add(sg);let stationsLocal=[{id:1,name:'Station Alpha (Vallée)',x:45,y:30,history:{temp:[],hum:[],wind:[],aqi:[]}},{id:2,name:'Station Bêta (Sommet)',x:22,y:15,history:{temp:[],hum:[],wind:[],aqi:[]}}],activeStation=0;
  function terrain(name){A.e.fill(.15);A.t.fill(18);A.h.fill(50);A.u.fill(1.5);A.v.fill(0);A.p.fill(5);A.c.fill(0);A.r.fill(0);A.su.fill(0);A.sv.fill(0);
   for(let y=0;y<H;y++)for(let x=0;x<W;x++){let e=.15,id=idx(x,y);
    if(name==='archipelago'){let d1=Math.hypot(x-25,y-20),d2=Math.hypot(x-65,y-40),d3=Math.hypot(x-45,y-45);e=d1<18?.1+(18-d1)*.04:d2<15?.1+(15-d2)*.05:d3<10?.1+(10-d3)*.03:.01;if(e<.05){A.h[id]=85;A.t[id]=20}}
    if(name==='valley'){let d=Math.abs(y-H/2);e=.1+(d/(H/2))**2*.75+Math.sin(x*.2)*.05;if(x<15&&y>20&&y<40)e=.01}
    if(name==='coastal'){if(x<30){e=.01;A.h[id]=90}else{e=.12+(x-30)/W*.3;if(x>50&&x<70&&y>20&&y<40){A.p[id]=80;A.t[id]=24}}}
    if(name==='desert'){e=.18+Math.sin(x*.1)*.08+Math.cos(y*.1)*.08;A.t[id]=34;A.h[id]=15;if(Math.hypot(x-45,y-30)<8){e=.02;A.h[id]=80;A.t[id]=26}}
    if(name==='plains'){e=.15+(Math.sin(x*.05)+Math.cos(y*.05))*.03;A.t[id]=19;A.h[id]=55}
    A.e[id]=clamp(e,0,1);
   }
   for(let z=0;z<N;z++)for(let x=0;x<N;x++){let gx=clamp(Math.floor(x/N*W),0,W-1),gy=clamp(Math.floor(z/N*H),0,H-1);pos.setY(z*N+x,A.e[idx(gx,gy)]*10-1.5)}geo.computeVertexNormals();paint();drawStations();
  }
  const cell=(x,z)=>({x:clamp(Math.floor((x/S+.5)*W),0,W-1),y:clamp(Math.floor((z/S+.5)*H),0,H-1)});
  const hAt=(x,y)=>A.e[idx(clamp(x,0,W-1),clamp(y,0,H-1)]);
  function oro(x,y){const id=idx(x,y),gx=A.e[idx(clamp(x+1,0,W-1),y)]-A.e[idx(clamp(x-1,0,W-1),y)],gy=A.e[idx(x,clamp(y+1,0,H-1))]-A.e[idx(x,clamp(y-1,0,H-1))],flow=gx*A.u[id]+gy*A.v[id];return{up:clamp(Math.max(0,flow)*2.5,0,1),dry:clamp(Math.max(0,-flow)*2.2+A.e[id]*.15,0,1),h:A.e[id]}};
  function paint(){const L=R.current.layer;for(let z=0;z<N;z++)for(let x=0;x<N;x++){const c=cell((x/N-.5)*S,(z/N-.5)*S),id=idx(c.x,c.y),e=A.e[id],t=A.t[id],h=A.h[id],r=A.r[id],w=Math.hypot(A.u[id],A.v[id])*10,p=A.p[id];let C=new THREE.Color;
    if(L==='temperature')C.setHSL(.7-clamp((t+20)/70,0,1)*.7,.82,.5);else if(L==='humidity')C.setHSL(.58-clamp(h/100,0,1)*.45,.75,.5);else if(L==='radar')C.setHSL(.55-clamp(r/30,0,1)*.55,.9,.5);else if(L==='wind')C.setHSL(.48-clamp(w/50,0,1)*.48,.8,.5);else if(L==='pollution')C.setHSL(.38-clamp(p/300,0,1)*.38,.75,.5);else if(L==='elevation')C.setHSL(.6-clamp(e,0,1)*.55,.55,.48);else{C.setHSL(.33,.45,.3+e*.25);if(A.c[id]>8)C.lerp(new THREE.Color(0xf2f6fa),clamp(A.c[id]/100*.7,0,.7));if(r>2)C.lerp(new THREE.Color(0x3b82c4),.18);if(p>20)C.lerp(new THREE.Color(0x9670a5),clamp((p-20)/250*.5,0,.5))}
    if(R.current.heatmap){const m=R.current.localMode,v=m==='temperature'?t:m==='humidity'?h:m==='wind'?w:r;C.lerp(new THREE.Color().setHSL(.66-clamp((v-([-20,0,0,0][['temperature','humidity','wind','rain'].indexOf(m)]||0))/([70,100,120,100][['temperature','humidity','wind','rain'].indexOf(m)]||100),0,1)*.66,.85,.55),.3)}
    col[(z*N+x)*3]=C.r;col[(z*N+x)*3+1]=C.g;col[(z*N+x)*3+2]=C.b;}geo.attributes.color.needsUpdate=true;waterMesh.material.opacity=R.current.water?.6:0}
  function tool(gx,gy,dx=0,dy=0){const rad=R.current.brush,pow=R.current.power/100;for(let oy=-rad;oy<=rad;oy++)for(let ox=-rad;ox<=rad;ox++){let x=gx+ox,y=gy+oy;if(x<0||x>=W||y<0||y>=H)continue;let d=Math.hypot(ox,oy);if(d>rad)continue;let f=(1-d/(rad+1))*pow,id=idx(x,y);switch(R.current.tool){
   case'raise':A.e[id]=clamp(A.e[id]+.05*f,0,1);break;case'lower':A.e[id]=clamp(A.e[id]-.05*f,0,1);break;case'smooth':{let s=0,n=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){let a=x+xx,b=y+yy;if(a>=0&&a<W&&b>=0&&b<H){s+=A.e[idx(a,b)];n++}}A.e[id]=lerp(A.e[id],s/n,f*1.7);break}
   case'heat':A.t[id]=clamp(A.t[id]+2*f,-20,50);break;case'cool':A.t[id]=clamp(A.t[id]-2*f,-20,50);break;case'humidify':A.h[id]=clamp(A.h[id]+5*f,0,100);break;case'dry':A.h[id]=clamp(A.h[id]-5*f,0,100);break;case'pollute':A.p[id]=clamp(A.p[id]+20*f,0,300);break;case'clean':A.p[id]=clamp(A.p[id]-20*f,0,300);break;
   case'wind_source':A.su[id]=clamp(A.su[id]+(dx?dx*1.2:ox/(rad+1))*2.5*f,-20,20);A.sv[id]=clamp(A.sv[id]+(dy?dy*1.2:oy/(rad+1))*2.5*f,-20,20);break;
   case'depression':A.su[id]=clamp(A.su[id]+(gx-x)/(rad+1)*3.5*f,-20,20);A.sv[id]=clamp(A.sv[id]+(gy-y)/(rad+1)*3.5*f,-20,20);A.h[id]=clamp(A.h[id]+6*f,0,100);A.c[id]=clamp(A.c[id]+8*f,0,100);break;
   case'anticyclone':A.su[id]=clamp(A.su[id]+(x-gx)/(rad+1)*3.5*f,-20,20);A.sv[id]=clamp(A.sv[id]+(y-gy)/(rad+1)*3.5*f,-20,20);A.c[id]=clamp(A.c[id]-12*f,0,100);A.h[id]=clamp(A.h[id]-8*f,0,100);A.r[id]=clamp(A.r[id]-10*f,0,100);break;
   case'thunderstorm':A.c[id]=clamp(A.c[id]+30*f,0,100);A.h[id]=clamp(A.h[id]+25*f,0,100);A.t[id]-=1.2*f;A.su[id]=clamp(A.su[id]+(Math.random()-.5)*10*f,-20,20);A.sv[id]=clamp(A.sv[id]+(Math.random()-.5)*10*f,-20,20);break;
   case'blizzard':A.t[id]=clamp(A.t[id]-4.5*f,-30,50);A.c[id]=clamp(A.c[id]+20*f,0,100);A.h[id]=clamp(A.h[id]+15*f,0,100);A.su[id]=clamp(A.su[id]-4*f,-20,20);break;}}
   for(let z=0;z<N;z++)for(let x=0;x<N;x++){let c=cell((x/N-.5)*S,(z/N-.5)*S);pos.setY(z*N+x,A.e[idx(c.x,c.y)]*10-1.5)}geo.computeVertexNormals();paint()}
  function step(){const r=R.current,rad=r.windDir*Math.PI/180,bu=-Math.cos(rad)*r.windSpeed/10,bv=-Math.sin(rad)*r.windSpeed/10,sun=(r.dayNight?Math.max(0,Math.cos(((hour-12)/12)*Math.PI)):1)*r.solar/100;hour=(Math.floor(tick/5)+12)%24;day=Math.floor(tick/120)+1;tick++;
   A.nt.set(A.t);A.nh.set(A.h);A.nc.set(A.c);A.np.set(A.p);
   for(let y=0;y<H;y++)for(let x=0;x<W;x++){let id=idx(x,y),gx=x>0&&x<W-1?A.e[idx(x+1,y)]-A.e[idx(x-1,y)]:0,gy=y>0&&y<H-1?A.e[idx(x,y+1)]-A.e[idx(x,y-1)]:0;A.u[id]=bu-gx*2+A.su[id];A.v[id]=bv-gy*2+A.sv[id];A.su[id]*=.992;A.sv[id]*=.992;let target=15+sun*12-A.e[id]*12+r.tempOffset;if(A.e[id]<.05)target=17+r.tempOffset;A.nt[id]+=(target-A.t[id])*.05;if(A.e[id]<.05)A.nh[id]=Math.min(100,A.nh[id]+A.t[id]/20*1.5*r.evap/100);let up=Math.max(0,A.u[id]*gx*5),eff=A.nh[id]+up*10;if(eff>75)A.nc[id]=Math.min(100,A.c[id]+(eff-75)*.8);else A.nc[id]=Math.max(0,A.c[id]-1);if(A.nc[id]>50){A.r[id]=(A.nc[id]-50)*.8;A.nh[id]=Math.max(0,A.nh[id]-A.r[id]*.3);A.nc[id]=Math.max(0,A.nc[id]-A.r[id]*.2)}else A.r[id]=0}
   for(let y=0;y<H;y++)for(let x=0;x<W;x++){let id=idx(x,y),sx=Math.round(x-A.u[id]),sy=Math.round(y-A.v[id]);if(sx>=0&&sx<W&&sy>=0&&sy<H){let q=idx(sx,sy);A.nh[id]=A.nh[id]*.7+A.h[q]*.3;A.nc[id]=A.nc[id]*.7+A.c[q]*.3;A.np[id]=A.np[id]*.7+A.p[q]*.3}if(r.pollution>0&&Math.random()<.05)A.np[id]+=r.pollution/10*2;if(A.r[id]>0)A.np[id]=Math.max(0,A.np[id]-A.r[id]*.2)}
   A.t.set(A.nt);for(let i=0;i<T;i++){A.h[i]=clamp(A.nh[i],0,100);A.c[i]=clamp(A.nc[i],0,100);A.p[i]=clamp(A.np[i],0,300)}telemetry();paint()}
  function telemetry(){let st=stationsLocal[activeStation],sum=[0,0,0,0];for(let i=0;i<T;i++){sum[0]+=A.t[i];sum[1]+=A.c[i];sum[2]+=A.r[i];sum[3]+=A.p[i]}setStats({temp:sum[0]/T,cloud:sum[1]/T,rain:sum[2]/T*.1,aqi:sum[3]/T});if(st){let id=idx(st.x,st.y),w=Math.hypot(A.u[id],A.v[id])*10;st.history.temp.push(A.t[id]);st.history.hum.push(A.h[id]);st.history.wind.push(w);st.history.aqi.push(A.p[id]);Object.values(st.history).forEach(a=>{if(a.length>30)a.shift()});setHistory({temp:[...st.history.temp],hum:[...st.history.hum],wind:[...st.history.wind],aqi:[...st.history.aqi]})}setStations([...stationsLocal])}
  function drawStations(){sg.clear();stationsLocal.forEach((s,i)=>{let g=new THREE.Group(),a=new THREE.Mesh(new THREE.CylinderGeometry(.05,.05,1.4,6),new THREE.MeshStandardMaterial({color:0xf59e0b})),b=new THREE.Mesh(new THREE.SphereGeometry(.18,8,8),new THREE.MeshStandardMaterial({color:i===activeStation?0x4ea1ff:0xffffff}));a.position.y=.7;b.position.y=1.45;g.add(a,b);g.position.set((s.x/W-.5)*S,hAt(s.x,s.y)*10-1.5,(s.y/H-.5)*S);sg.add(g)})}
  let painting=false,lastCell=null,tick=0,hour=12,day=1,acc=0,last=performance.now(),ui=0;const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
  function getCell(e){let b=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-b.left)/b.width*2-1;mouse.y=-(e.clientY-b.top)/b.height*2+1;ray.setFromCamera(mouse,camera);let hit=ray.intersectObject(ground)[0];return hit?cell(hit.point.x,hit.point.z):null}
  function pointerDown(e){if(e.button!==0)return;let c=getCell(e);if(!c)return;painting=true;controls.enabled=false;lastCell=c;if(R.current.tool==='station'){stationsLocal.push({id:stationsLocal.length+1,name:'Station '+(stationsLocal.length+1),x:c.x,y:c.y,history:{temp:[],hum:[],wind:[],aqi:[]}});activeStation=stationsLocal.length-1;setStation(activeStation);drawStations()}else if(R.current.tool==='inspect')inspect(c);else tool(c.x,c.y)}
  function pointerMove(e){let c=getCell(e);if(!c)return;if(R.current.tool==='inspect'&&!painting)inspect(c);if(painting&&!['station','inspect'].includes(R.current.tool)){tool(c.x,c.y,lastCell?c.x-lastCell.x:0,lastCell?c.y-lastCell.y:0);lastCell=c}}
  function inspect(c){let id=idx(c.x,c.y),w=Math.hypot(A.u[id],A.v[id])*10;setPoint({temp:A.t[id],hum:A.h[id],wind:w,rain:A.r[id]});}
  renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',()=>{painting=false;controls.enabled=true;lastCell=null});
  function scenarioApply(id){let s=SCENARIOS[id];terrain(s[3]==='plaine'?'plains':s[3]==='montagne'?'valley':s[3]==='ocean'?'coastal':s[3]==='foret'?'plains':'desert');A.t.fill(s[4]);A.h.fill(s[5]);A.u.fill(s[6]/10);A.v.fill(0);A.c.fill(id==='front'||id==='tempete'?60:0);A.r.fill(id==='front'||id==='tempete'?50:0);paint()}
  function frame(now){if(!alive)return;let dt=Math.min(.05,(now-last)/1000);last=now,ui+=dt;if(R.current.running){acc+=dt*R.current.speed*6;while(acc>=1){acc--;step();if(R.current.speed<.5)break}}clouds.forEach(g=>{let c=cell(g.position.x,g.position.z),o=oro(c.x,c.y);g.position.x+=(R.current.windSpeed+10)*.018*dt;if(g.position.x>30)g.position.x=-30;g.position.y=14+o.h*3+o.up*4;g.scale.setScalar(.8+o.up*.65);g.children.forEach(m=>m.material.opacity=.5+o.up*.4-o.dry*.18)});for(let i=0;i<particles.length;i++){let p=particles[i],x=Math.floor(p.x),y=Math.floor(p.y);if(x>=0&&x<W&&y>=0&&y<H){let q=idx(x,y);p.x+=A.u[q]*.3;p.y+=A.v[q]*.3}p.l++;if(p.l>p.m||p.x<0||p.x>=W||p.y<0||p.y>=H){p.x=Math.random()*W;p.y=Math.random()*H;p.l=0}pp[i*3]=(p.x/W-.5)*S;pp[i*3+1]=2;pp[i*3+2]=(p.y/H-.5)*S}pg.attributes.position.needsUpdate=true;if(ui>.5){ui=0;let o=oro(45,30);setRelief({lift:Math.round(o.up*100),dry:Math.round(o.dry*100),rain:Math.round(o.up*A.h[idx(45,30)]*.9)})}waterMesh.material.opacity=R.current.water?(0.55+0.08*Math.sin(now*.002)):0;controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)}
  terrain('valley');drawStations();E.current={terrain,step,scenarioApply,paint,clearClouds:()=>{A.c.fill(0);A.r.fill(0);paint()},clearPollution:()=>{A.p.fill(0);paint()},deleteStation:()=>{if(stationsLocal.length>1){stationsLocal.splice(activeStation,1);activeStation=0;setStation(0);drawStations()}},selectStation:i=>{activeStation=i;drawStations();telemetry()}};requestAnimationFrame(frame);
  return()=>{alive=false;renderer.dispose();root.innerHTML=''};
 },[]);
 useEffect(()=>{R.current.preset=preset;if(E.current)E.current.terrain(preset)},[preset]);
 useEffect(()=>{if(E.current)E.current.paint()},[layer,heatmap,localMode,water]);
 useEffect(()=>{if(E.current&&scenario!=='custom')E.current.scenarioApply(scenario)},[scenario]);
 useEffect(()=>{if(E.current)E.current.selectStation(station)},[station]);

 const local=point||{temp:20,hum:50,wind:windSpeed,rain:0};const b=TYPES[biome];const condition=local.rain>65?'🌧️ Pluie':local.temp<0?'❄️ Neige':relief.dry>65?'☀️ Ombre pluviométrique':local.hum>78?'🌧️ Humide':'⛅ Nuageux';
 return <div className="app"><header><div><span className="eyebrow">AEROSIM 3D / WEATHER LAB</span><h1>Weather Sandbox</h1><p>Portage du moteur méso-climatique AeroSim 2D dans le terrain 3D React/Three.js.</p></div><div className="status">● {running?'SIMULATION ACTIVE':'PAUSE'} · J{day} {String(hour).padStart(2,'0')}:00</div></header>
 <main><section className="world"><div className="viewport" ref={mount}/><div className="layerbar">{Object.entries(LAYERS).map(([k,v])=><button className={layer===k?'selected':''} onClick={()=>setLayer(k)} key={k}>{v}</button>)}</div>
 <div className="tools"><div className="tool-grid">{Object.entries(TOOLS).map(([k,v])=><button className={tool===k?'on':''} onClick={()=>setTool(k)} key={k}>{v}</button>)}</div><div className="tool-controls"><label>Pinceau <input type="range" min="1" max="15" value={brush} onChange={e=>setBrush(+e.target.value)}/>{brush}</label><label>Intensité <input type="range" min="10" max="100" value={power} onChange={e=>setPower(+e.target.value)}/>{power}%</label><button onClick={()=>setRunning(!running)}>{running?'⏸ Pause':'▶ Reprendre'}</button><button onClick={()=>E.current&&E.current.step()}>⏭️ Pas</button><select value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.1,.25,.5,1,2,5,10,20].map(x=><option key={x} value={x}>{x}x</option>)}</select></div></div>
 <div className="readings"><Metric label="Température" value={local.temp} unit="°C"/><Metric label="Humidité" value={local.hum} unit="%"/><Metric label="Vent" value={local.wind} unit=" km/h"/><Metric label="Conditions" value={condition}/></div>{point&&<div className="inspector">🔎 Point : {point.temp.toFixed(1)}°C · {Math.round(point.hum)}% · {Math.round(point.wind)} km/h · pluie {Math.round(point.rain)}%</div>}</section>
 <aside><Panel title="Terrain & presets"><select className="full" value={preset} onChange={e=>setPreset(e.target.value)}>{Object.entries(PRESETS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="wide" onClick={()=>E.current&&E.current.terrain(preset)}>↺ Réinitialiser</button></Panel>
 <Panel title="Scénarios"><div className="scenario-grid">{Object.entries(SCENARIOS).map(([k,s])=><button className={scenario===k?'selected':''} onClick={()=>{setScenario(k);setBiome(s[3])}} key={k}><b>{s[0]} {s[1]}</b><small>{s[2]}</small></button>)}</div><button className="wide" onClick={()=>setScenario('custom')}>⚙️ Mode libre</button></Panel>
 <Panel title="Biome"><div className="terrain-grid">{Object.entries(TYPES).map(([k,v])=><button className={biome===k?'selected':''} onClick={()=>setBiome(k)} key={k}>{v.icon} {k}</button>)}</div><p>Température <strong>{b.temp>=0?'+':''}{b.temp}°C</strong></p><p>Humidité <strong>{b.humidity>=0?'+':''}{b.humidity}%</strong></p><p>Vent <strong>{b.wind>=0?'+':''}{b.wind} km/h</strong></p></Panel>
 <Panel title="🌦️ Micro-climat local"><div className="local-modes">{Object.entries(MODES).map(([k,v])=><button className={localMode===k?'selected':''} onClick={()=>{setLocalMode(k);setLocalValue(k==='temperature'?20:k==='humidity'?55:k==='wind'?15:0)}} key={k}>{v[0]}</button>)}</div><Control label={MODES[localMode][0]} value={localValue} min={MODES[localMode][2]} max={MODES[localMode][3]} unit={MODES[localMode][1]} set={setLocalValue}/><label className="check"><input type="checkbox" checked={heatmap} onChange={e=>setHeatmap(e.target.checked)}/> Carte thermique</label><p className="hint">Les outils météo (chauffage, humidification, pollution, vents, phénomènes) s'appliquent localement au pinceau.</p></Panel>
 <Panel title="Paramètres globaux"><Control label="Solaire" value={solar} min={0} max={200} unit="%" set={setSolar}/><Control label="Biais température" value={tempOffset} min={-15} max={15} unit="°C" set={setTempOffset}/><Control label="Vent global" value={windSpeed} min={0} max={50} unit=" km/h" set={setWindSpeed}/><Control label="Direction du vent" value={windDir} min={0} max={360} unit="°" set={setWindDir}/><Control label="Émissions pollution" value={pollution} min={0} max={100} unit="%" set={setPollution}/><Control label="Évaporation" value={evap} min={20} max={200} unit="%" set={setEvap}/><label className="check"><input type="checkbox" checked={dayNight} onChange={e=>setDayNight(e.target.checked)}/> Cycle jour / nuit</label><label className="check"><input type="checkbox" checked={water} onChange={e=>setWater(e.target.checked)}/> Eau visible</label></Panel>
 <Panel title="Stations météo"><select className="full" value={station} onChange={e=>setStation(+e.target.value)}>{stations.map((s,i)=><option key={s.id} value={i}>{s.name}</option>)}</select><div className="station-values"><Metric label="Temp" value={stations[station]?.history.temp.at(-1)||0} unit="°C"/><Metric label="Hum" value={stations[station]?.history.hum.at(-1)||0} unit="%"/><Metric label="Vent" value={stations[station]?.history.wind.at(-1)||0} unit=" km/h"/><Metric label="AQI" value={stations[station]?.history.aqi.at(-1)||0}/></div><MiniCharts data={history}/><button className="wide" onClick={()=>E.current&&E.current.deleteStation()}>🗑 Supprimer</button><small>Active l'outil 📍 Station puis clique sur le terrain.</small></Panel>
 <Panel title="Statistiques"><div className="station-values"><Metric label="Temp. moyenne" value={stats.temp} unit="°C"/><Metric label="Nuages" value={stats.cloud} unit="%"/><Metric label="Pluie" value={stats.rain} unit=" mm/h"/><Metric label="AQI" value={stats.aqi}/></div></Panel>
 <Panel title="Actions rapides"><div className="row"><button onClick={()=>E.current&&E.current.clearClouds()}>☁️ Chasser nuages</button><button onClick={()=>E.current&&E.current.clearPollution()}>🧼 Nettoyer air</button></div></Panel>
 <Panel title="Physique du relief"><p>Ascendance <strong>{relief.lift}%</strong></p><p>Zone sèche <strong>{relief.dry}%</strong></p><p>Pluie orographique <strong>{relief.rain}%</strong></p></Panel></aside></main></div>
}
function Panel({title,children}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Control({label,value,min,max,unit,set}){return <div className="control"><div><label>{label}</label><b>{Number(value).toFixed(Number.isInteger(value)?0:1)}{unit}</b></div><input type="range" min={min} max={max} step={label==='Biais température'?.5:1} value={value} onChange={e=>set(+e.target.value)}/></div>}
function Metric({label,value,unit=''}){return <div><span>{label}</span><b>{typeof value==='string'?value:Number(value||0).toFixed(1)+unit}</b></div>}
function MiniCharts({data}){const p=a=>a.map((v,i)=>i+', '+(100-v)).join(' ');return <div className="charts"><div><small>Température / humidité</small><svg viewBox="0 0 30 100" preserveAspectRatio="none"><polyline points={p(data.temp)} fill="none" stroke="#f43f5e" strokeWidth="1.5"/><polyline points={p(data.hum)} fill="none" stroke="#22d3ee" strokeWidth="1.5"/></svg></div><div><small>Vent / AQI</small><svg viewBox="0 0 30 100" preserveAspectRatio="none"><polyline points={p(data.wind)} fill="none" stroke="#2dd4bf" strokeWidth="1.5"/><polyline points={p(data.aqi)} fill="none" stroke="#c084fc" strokeWidth="1.5"/></svg></div></div>}
createRoot(document.getElementById('root')).render(<App/>);